apiVersion: v1
kind: Service
metadata:
  name: secroute
spec:
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 0
---
apiVersion: v1
kind: Endpoints
metadata:
  name: secroute
subsets:
- addresses:
  - ip: 172.20.10.5
  ports:
  - name: http
    port: 8080

#kind: DeploymentConfig
#apiVersion: "v1"
#metadata:
#  labels:
#    app: "chuck-api"
#  name: "chuck-api"
#  namespace: "chuck"
#spec:
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        app: "chuck-api"
#    spec:
#      containers:
#      - name: "chuck-api"
#        image: "dimssss/op-test"
#        imagePullPolicy: Always

#apiVersion: v1
#kind: Service
#metadata:
#  name: secroute
#spec:
#  type: ExternalName
#  externalName: 172.20.10.5



#apiVersion: v1
#kind: Service
#metadata:
#  name: my-service
#spec:
#  type: ExternalName
#  externalName: secroute.dev.local