apiVersion: v1
kind: Service
metadata:
  name: secroute
spec:
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 0
---
apiVersion: v1
kind: Endpoints
metadata:
  name: secroute
subsets:
- addresses:
  - ip: 172.20.10.5
  ports:
  - name: http
    port: 8080
