apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validate-external-service
  labels:
    app: validate-external-service
webhooks:
  - name: validate-external-service.dev.local
    clientConfig:
      url: https://secroute.dev.local:8080/service/validate
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRFhiTkpmZnNZZW56QU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NVGt3T1RJd01EZ3pPRE01V2hnUE1qRXhPVEE0TWpjd09ETTRNemxhTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU1uYUUvSGV2Z0dQTGlvc1puNFR0aE1OeXpjbUlNak1UZnVJSlNLTHVHT0hhUjZmWm1ZelhUVGgKTkw1aVJSSFZ4clpsdnNZQ3RvNE1mQkdta01RaWJkWGV0OGdXRzJnNFhHQUU4NTJtS2x1TkZaT0gzM2tWek1jYwpkakNSTmlTMytrdVljcDFWQ3FlOVcvaUVIdWhvZTF0bTlNakxPaHJlbGl4Um44TEJCMmxwbTF0eXozWnJWY0Z2CnEwZlhlbTJGTmxzeHZUV0dvR29qL0hLd29ldE9kbzZWa1lOTEliVUxPUURlSmx3YThHZzdCemdIcDQweXVIVEEKQlNOZmdRSDRjdFd0YkdFaGd6Rzk5UjFUYkZ2emRna0MrZ1EvTCtiZ04xcUVaTml4OXd6QXZ0MTRWZWVUdTBYRQo3QlM1TVNnb3ZzMGxNV211aGRkb0dJMWpDS2RmS2lzQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCnR3ZVBwUGx4cUxoMjcvZlpDZGxEQjArMGZyazZoaHZkQjdmR0xFM2t6SW5VVklWaUpiN3kwcFFuTjdMc1VTYXQKRXRJeU43d1QwMlo2RUVWUE45TUFocjVjU216S2JYSmRua0pVYjNrT2pTeWVyLzZxVzhuRXYrMXdReUY0VHFpYQo1WWdXSlVqVFl2NWM3TlVRTHNqVGNEdm8xMjRRc1RnOTEyM2dQMlg0RmdZeTdIc3BXYlU0dUhYREtQUkxvTHNyCloySzh0U3daVzdVaHhBcjdTTERyaXlOaFcyZ1ZNVFQyVFV0Z2JjKzhHam5yMjc1TjQ2SkE3LytGUVhHVVhNVnIKMjJGSUE0cVJKS1RYTzk0ZElVRFhIYkl5ZmNuU0RyYjFjc1BMSldyVlVaUG1xZ01pTSthVDNLaG9JOGY3WXZNRQpUSW5iWXgzYUZGSCtRaWFSL1orTENBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["services"]
    failurePolicy: Ignore