apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validate-external-service-side-effect
  labels:
    app: validate-external-service-side-effect
webhooks:
  - name: validate-external-service.dev.local
    sideEffects: NoneOnDryRun
    clientConfig:
      url: https://secroute.dev:8080/route/validate
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRFJQK0RtZXdUU2J6QU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NVGt3T1RJeU1EVTBNakl4V2hnUE1qRXhPVEE0TWprd05UUXlNakZhTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU5hZEFBRlR3b0dveFNxdnN5RzNxTGhjajE5bjZCakZzM05GZ2dHSXRsZUFTOUtpWll2a3hQQWMKTDBQcEJtaWRsdmVQUTY5MUdranBZa01OOTJJejhMYnY0ekJrL0pWYzIvcjRiajVMdUp4WE1jazlxQTJIM0ZYcQpPZUQ4Z1pWTzRxUHIwNVhET3B0UjJtV2pXN1RiQ01oRis0eFBFUitwQ04zNUlyVlY3TXpxeWlYbHBReThUUmpPCm9HZjIrU3JFVEVNY2JSMU9qTkZOWFJ6amhSTDRCUFoxT1FneTR3RXYzeDl4L3V1aGNibGdtYy80aVlJRWJldVEKUlU3WW0yR0FoZHozWFlVWWhTZ1hlaVNpdFNlMlJ1dkE2UWF4RFY4SktmcWNhZzFRUnlUOEgrUEVTYzI2SmZabQpIaC9Vd1NwNUNCbGE3ZVBvYkI2N0lpN3EvY3pyOFdjQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBClZ5bk1LTlNHWXJVV29YemRxaWtaeERjMXNRemFWc1pKbUxDM0ZTbDRUeEpUWWtzZnBLU0R3MmNDQVE0T3c4S1IKNGZVZDN0cDVPSHdCTkZQNnFEOHdGdXB6ZVh0NVR2ODZLQklFTk9IaVlBTVFuZHRHWTREb1FhQlpNNnFNcTZLbQp2M1FVNmhSQmpZU2E2eVB5aElscEl5WGR3d2w1dzdFZ0ZKdFk4RTlvRFRKMUZQT3ZqQUxWL3pXRGhJd2UzdlhLCitzZ2FZVU00Mm1SaVl5Qm1oN0VSRHM5Mzd5TzFpcExYdU1hL3FqUTYwcTJKMHdBK0NQejg3SkF3Ry94aG1aUm0KOUxDOTVSaVB2K3R6NFZzQVZ4aEswVStoOTRXK0lHTUc1alpZVTh0a3ZuZkphL29jY3pwcDdZM1V2KzBNT2xuWgp5K2NJM0taV0V1Q1ZsZlB0VEt2OUFnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - operations: [ "CREATE", "DELETE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["services"]
