apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    addRoute: "true"
spec:
  type: ClusterIP
  selector:
    docker-registry: demo-app
  ports:
  - name: http
    port: 80
    protocol: TCP
