apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: uac
  labels:
    app: uac
webhooks:
  - name: uac-webhook.uac-webhook.svc.cluster.local
    clientConfig:
      url: https://uac-webhook.uac-webhook.svc.cluster.local:8080/
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRG83YXMwMnVTQmR6QU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NVGt3T0RBNU1USXlOekV6V2hnUE1qRXhPVEEzTVRZeE1qSTNNVE5hTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUpPcUlIeTVwVEt4ZlBkMEtLRkdrQmxKT0FraFU0eWtUSE0xQXJKd0QyS2Q4bTI4b3J3OXB2RWsKTmpZVmxEN01NM1ArRnFlQW1NSGVKTEk0V2oyeGtPZlJOdlVlVG1PeHBkWEM3TVc1cEtYRi9EUDM0ZEYrWFZVSAp6bmJCWTNMWEZIVEtYYVNvVWlCOEpjWm9ZYlhsMUVVWDlSNkI1RmtpaTNhaUhNMnZxSUY4K29pSHBDZmlOUkFlCmJXb2YzM24zVmpITC9PL1RyTTFsditLQUUzdGFJeTNTQXNqMmluVUZZKzZrOVBGWXdDWGRhQWJCZzdmNkpabWUKR21YQnM2Y1RvWkRkaWNIYmg1RFlsekZDczBrRlo3KzB5V0REVk5XSS9uKzJjVWl2NXViMHVNeHRNdUhwc0d1YQpFQkhCdHU4RXZqUUxFWTFHVnFtbVZmWXY3bUkzRmFVQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBClFIOHNGS1k5TlRDNmZ3ZmFoOXU5RjE0a0dYSlAyTHJCMzJqc1U2R09GSnNtSE9WMmlNcjVnQUhQWTZ0N2t4NSsKL3h6Z2Q4VHc2WHVRbkhvMW9TU0RiR084bHBzTGFxejloQTZmcjE3V0Njajd2cnh6SGFFWlhBRHpnYnFQTVJ0NApMUCsvcWZEdzVINms1YUdTRlJ4bXZLZ3F3b3FrU2cvRFA1c2NqZW1WN2hTdEp6TmptRDU0aU1xZWhmczczS1ZuCnhaRXh6UHFjOUZGY0IvSTBCMy9BeWJCZUI3dTNpWU43MzUyT2RkVUt5dzMyVFkrS241alVyYWM0RDBDR09hTjgKaXdwOWtsYUZ3ZXkyelJUZCt5TzBGNWpmU1RsWVNieUZwcGFHWFhMalNraU5nWW52eGtRbjQ1UlFkM2E4UDFsQgpQcU9HbFNza3Y5L2dYa1c2aXgrUGFBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["oauthaccesstokens"]
    failurePolicy: Ignore
